
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 30 12:09:31 CST 2024
//----------------------------------------------------

package compiladores_2023b;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 29;
  public static final int Llave_c = 36;
  public static final int Double = 8;
  public static final int Op_booleano = 32;
  public static final int Llave_a = 35;
  public static final int If = 18;
  public static final int T_dato = 16;
  public static final int Byte = 4;
  public static final int Clase = 13;
  public static final int Else = 19;
  public static final int Corchete_c = 38;
  public static final int Corchete_a = 37;
  public static final int Long = 6;
  public static final int Punto = 12;
  public static final int While = 21;
  public static final int M_Package = 10;
  public static final int Division = 27;
  public static final int Int = 2;
  public static final int Cadena = 17;
  public static final int Float = 7;
  public static final int Parentesis_c = 34;
  public static final int Parentesis_a = 33;
  public static final int For = 22;
  public static final int P_coma = 40;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Linea = 14;
  public static final int Char = 5;
  public static final int Op_atribucion = 30;
  public static final int ERROR = 43;
  public static final int Do = 20;
  public static final int Op_logico = 28;
  public static final int String = 3;
  public static final int Identificador = 41;
  public static final int Resta = 25;
  public static final int Boolean = 9;
  public static final int Multiplicacion = 26;
  public static final int Op_incremento = 31;
  public static final int Numero = 42;
  public static final int Suma = 24;
  public static final int Main = 39;
  public static final int Igual = 23;
  public static final int Modificadores_acceso = 11;
  public static final int Comillas = 15;
}

